// <auto-generated />
namespace KoscielniakInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jobupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201701242006557_job-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
